apiVersion: v1
kind: ConfigMap
metadata:
  name: dealbot-env
  labels:
    app.kubernetes.io/name: dealbot
data:
  DATABASE_HOST: "postgres"
  DATABASE_NAME: "filecoin_dealbot"
  DATABASE_PORT: "5432"
  DATABASE_USER: "dealbot"
  DEALBOT_HOST: "0.0.0.0"
  DEALBOT_PORT: "3130"
  NODE_ENV: "production"
