apiVersion: v1
kind: Service
metadata:
  name: dealbot
  labels:
    app.kubernetes.io/name: dealbot
spec:
  type: ClusterIP
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dealbot
